version = 1

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "php"

[[analyzers]]
name = "sql"

[[analyzers]]
name = "csharp"